services:
  financial_document_summarizer:
    build: .
    container_name: financial_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
